# Generated by Django 4.1.2 on 2022-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cart_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
