# Generated by Django 4.1.2 on 2022-11-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_orderitem_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
